[tool.poetry]
name = "gomagic"
version = "0.1.0"
description = ""
authors = ["Caspar Luc <luc.caspar@cross-compass.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.3"
scikit-learn = "^1.5.2"
numpy = "^2.1.3"
scipy = "^1.14.1"
matplotlib = "^3.9.3"
pyamg = "^5.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
